name: Build and release
on:
  push:
    tags:
      - v*

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 'Change version'
        uses: reedyuk/npm-version@1.1.1
        with:
          version: ${{ github.ref_name }}

      - name: Build and Test
        run: |
          npm i && npm run build && npm run test

      - name: Automatically release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          title: 'Development Build'
          files: |
            dist/index.js
            dist/index.js.map
            dist/index.cjs
            dist/index.cjs.map
            dist/index.d.cts
            dist/index.d.ts

      - name: Publish npm package
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_JS_TOKEN }}
          registry: 'https://registry.npmjs.org'
          dry-run: true
